services:
  server:
    build: ./server
    container_name: express_server
    ports:
      - "5000:5000"
    networks:
      - fullstack-net
    restart: unless-stopped

  client:
    build: ./client
    container_name: react-client
    ports:
      - "5173:3000"
    depends_on:
      - server
networks:
  fullstack-net:
    driver: bridge
